// Generated by CoffeeScript 1.6.3
(function($) {
  return $.fn.extend({
    submitByEnter: function() {
      var _this = this;
      return this.on('keypress', function(event) {
        if (event.which === 13 && !event.shiftKey && !event.ctrlKey && _this.val().replace(/^\s+|\s+$/g, "").length > 0) {
          _this.closest('form').submit();
          return event.preventDefault();
        }
      });
    }
  });
}).call(this, jQuery);

(function($) {
  return true;
}).call(this, jQuery);
