// Generated by CoffeeScript 1.6.3
(function($) {
  return $.fn.extend({
    preventParentScroll: function() {
      var _this = this;
      return this.bind('mousewheel', function(event) {
        var delta, height, scrollHeight, scrollTop;
        height = _this.height();
        scrollHeight = _this.prop('scrollHeight');
        scrollTop = _this.prop('scrollTop');
        delta = event.originalEvent.wheelDelta;
        if ((scrollTop === (scrollHeight - height) && delta < 0) || (scrollTop === 0 && delta > 0)) {
          return event.preventDefault();
        }
      });
    }
  });
}).call(this, jQuery);

(function($) {
  return $.fn.extend({
    submitByEnter: function() {
      var _this = this;
      return this.on('keypress', function(event) {
        if (event.which === 13 && !event.shiftKey && !event.ctrlKey && _this.val().replace(/^\s+|\s+$/g, "").length > 0) {
          _this.closest('form').submit();
          return event.preventDefault();
        }
      });
    }
  });
}).call(this, jQuery);

(function($) {
  return true;
}).call(this, jQuery);
